# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-10 17:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventslist',
            name='res_person_workplace',
            field=models.CharField(default='NULL', max_length=30),
        ),
        migrations.AddField(
            model_name='eventslist',
            name='resourceperson',
            field=models.CharField(default='NULL', max_length=30),
        ),
        migrations.AlterField(
            model_name='resourceusage',
            name='date',
            field=models.DateField(default=datetime.datetime(2016, 8, 10, 22, 49, 55, 270000)),
        ),
    ]
