# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-13 06:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0004_auto_20160812_0528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourceusage',
            name='date',
            field=models.DateField(default=datetime.datetime(2016, 8, 13, 12, 24, 36, 693000)),
        ),
    ]
